
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FLOAT_LIT = 58;
  public static final int SEQ = 8;
  public static final int FORALL = 33;
  public static final int CHAR_LIT = 54;
  public static final int POW = 21;
  public static final int CHAR = 2;
  public static final int CONCAT = 12;
  public static final int RET = 34;
  public static final int LTHANEQ = 23;
  public static final int EQUALS = 24;
  public static final int LPAREN = 39;
  public static final int INT = 4;
  public static final int RAT_LIT = 57;
  public static final int ENDDO = 38;
  public static final int MINUS = 18;
  public static final int RPAREN = 40;
  public static final int NOT = 13;
  public static final int AND = 14;
  public static final int LTHAN = 22;
  public static final int NEQUALS = 25;
  public static final int IN = 10;
  public static final int OR = 15;
  public static final int TDEF = 26;
  public static final int COMMA = 45;
  public static final int BOOL = 3;
  public static final int SEMICOL = 47;
  public static final int DIV = 20;
  public static final int RAT = 5;
  public static final int PLUS = 17;
  public static final int MAIN = 49;
  public static final int ASSIGN = 35;
  public static final int IF = 28;
  public static final int ID = 53;
  public static final int DOT = 36;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int STR_LIT = 59;
  public static final int FDEF = 27;
  public static final int IMPLY = 16;
  public static final int LBRACK = 43;
  public static final int TOP = 9;
  public static final int COL = 46;
  public static final int TIMES = 19;
  public static final int ENDIF = 37;
  public static final int LBRACE = 41;
  public static final int DICT = 7;
  public static final int ELSE = 30;
  public static final int READ = 51;
  public static final int RBRACK = 44;
  public static final int WHILE = 31;
  public static final int FLOAT = 6;
  public static final int RBRACE = 42;
  public static final int THEN = 29;
  public static final int BOOL_LIT = 55;
  public static final int LEN = 11;
  public static final int ALIAS = 50;
  public static final int RANGBR = 48;
  public static final int INT_LIT = 56;
  public static final int PRINT = 52;
  public static final int DO = 32;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CHAR",
  "BOOL",
  "INT",
  "RAT",
  "FLOAT",
  "DICT",
  "SEQ",
  "TOP",
  "IN",
  "LEN",
  "CONCAT",
  "NOT",
  "AND",
  "OR",
  "IMPLY",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "POW",
  "LTHAN",
  "LTHANEQ",
  "EQUALS",
  "NEQUALS",
  "TDEF",
  "FDEF",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "DO",
  "FORALL",
  "RET",
  "ASSIGN",
  "DOT",
  "ENDIF",
  "ENDDO",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACK",
  "RBRACK",
  "COMMA",
  "COL",
  "SEMICOL",
  "RANGBR",
  "MAIN",
  "ALIAS",
  "READ",
  "PRINT",
  "ID",
  "CHAR_LIT",
  "BOOL_LIT",
  "INT_LIT",
  "RAT_LIT",
  "FLOAT_LIT",
  "STR_LIT"
  };
}

